#!/usr/bin/env python3
"""Relocation, file inventories and safe extraction for the Iollo runtime."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import sys
import tarfile

from release import check_archive, digest


def prepare(root):
    site = root / "python/lib" / f"python{sys.version_info.major}.{sys.version_info.minor}" / "site-packages"
    # The wheel omits runtime assets and some namespace packages. Preserve the
    # source checkout layout for all Python entry points, including subprocesses.
    (site / "iollo-source.pth").write_text(
        'import sys; from pathlib import Path; sys.path.insert(0, str(Path(sys.prefix).parent / "hermes"))\n'
    )
    for path in (root / "python/bin").iterdir():
        if path.is_symlink() or not path.is_file():
            continue
        data = path.read_bytes()
        if not data.startswith(b"#!"):
            continue
        lines = data.split(b"\n")
        if b"python" in lines[0]:
            body = b"\n".join(lines[1:])
        elif len(lines) > 3 and lines[1].startswith(b"'''exec'") and b"python" in lines[1]:
            body = b"\n".join(lines[3:])
        else:
            continue
        # pip's absolute shebangs break when the app moves the runtime directory.
        prefix = b'''#!/bin/sh\n''' + b"'''exec' \"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)/python3\" \"$0\" \"$@\"\n' '''\n"
        path.write_bytes(prefix + body)
    # These are generated by pip, not tracked runtime source/data.
    shutil.rmtree(root / "hermes/build", ignore_errors=True)
    shutil.rmtree(root / "hermes/hermes_agent.egg-info", ignore_errors=True)


def inventory(root):
    files = []
    for path in sorted(root.rglob("*")):
        name = path.relative_to(root).as_posix()
        if name == "MANIFEST.json":
            continue  # Self-hashing is impossible; the archive hash covers this file.
        if path.is_symlink():
            target = os.readlink(path)
            if not path.resolve().is_relative_to(root.resolve()):
                raise ValueError(f"External symlink: {name}")
            files.append({"path": name, "type": "symlink", "target": target,
                          "sha256": hashlib.sha256(os.fsencode(target)).hexdigest()})
        elif path.is_file():
            files.append({"path": name, "type": "file", "sha256": digest(path),
                          "size": path.stat().st_size, "mode": path.stat().st_mode & 0o777})
    return files


def extract(tar_path, destination, name):
    """Reject traversal/special files before extracting; works on Apple's Python 3.9."""
    with tarfile.open(tar_path) as archive:
        members = archive.getmembers()
        seen = set()
        links = set()
        for member in members:
            path = PurePosixPath(member.name)
            if path.is_absolute() or ".." in path.parts or not path.parts or path.parts[0] != name:
                raise ValueError(f"Unsafe archive path: {member.name}")
            if path in seen:
                raise ValueError(f"Duplicate archive path: {member.name}")
            seen.add(path)
            if not (member.isdir() or member.isfile() or member.issym() or member.islnk()):
                raise ValueError(f"Special archive entry: {member.name}")
            if member.issym() or member.islnk():
                links.add(path)
                parent = path.parent if member.issym() else PurePosixPath()
                target = (destination / parent / member.linkname).resolve()
                if not target.is_relative_to((destination / name).resolve()):
                    raise ValueError(f"External archive link: {member.name}")
        for member in members:
            if any(parent in links for parent in PurePosixPath(member.name).parents):
                raise ValueError(f"Archive writes through a link: {member.name}")
        # Write regular files before links; never let tar follow an archive symlink.
        for member in members:
            path = destination / member.name
            if member.isdir():
                path.mkdir(parents=True, exist_ok=True)
            elif member.isfile():
                path.parent.mkdir(parents=True, exist_ok=True)
                with archive.extractfile(member) as source, path.open("xb") as output:
                    shutil.copyfileobj(source, output)
                path.chmod(member.mode & 0o777)
        for member in members:
            path = destination / member.name
            if member.issym() or member.islnk():
                path.parent.mkdir(parents=True, exist_ok=True)
                if member.issym():
                    path.symlink_to(member.linkname)
                else:
                    target = destination / member.linkname
                    if not target.is_file() or PurePosixPath(member.linkname) in links:
                        raise ValueError(f"Invalid hard link: {member.name}")
                    os.link(target, path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("prepare", "manifest"):
        child = sub.add_parser(command)
        child.add_argument("root", type=Path)
    unpack = sub.add_parser("unpack")
    unpack.add_argument("archive", type=Path)
    unpack.add_argument("tar", type=Path)
    unpack.add_argument("destination", type=Path)
    args = parser.parse_args()
    if args.command == "prepare":
        prepare(args.root)
    elif args.command == "manifest":
        (args.root / "MANIFEST.json").write_text(json.dumps({"files": inventory(args.root)}, indent=2) + "\n")
    else:
        metadata, asset = check_archive(args.archive)
        name = args.archive.name.removesuffix(".tar.zst")
        extract(args.tar, args.destination, name)
        root = args.destination / name
        if (root / "VERSION").read_text().strip() != metadata["tag"]:
            raise ValueError("VERSION differs from release.json")
        if json.loads((root / "MANIFEST.json").read_text())["files"] != inventory(root):
            raise ValueError("MANIFEST.json differs from extracted files")
        print(f"Verified every manifest entry for {asset['arch']}")
