"""The iollo typed-note format (brief 003). Standard library only: the box consolidation job
(iollo brief 032) imports this module, so it must not pull in the agent runtime.

A note lives at ``<type folder>/<slug>.md`` under the notes directory::

    ---
    id: people/ana-costa
    type: person
    aliases: [Ana, Ana Costa]
    updated: 2026-09-24
    ---
    # Ana Costa
    - 2026-09-24 Ricardo's dentist in Lisbon, see [[organizations/clinica-sorriso]]. (from: box, whatsapp)
    - 2026-09-24 Away until mid-October. {valid_until: 2026-10-15} (from: mac:3f2a, conversation 8c1d)

``USER.md`` at the root is generated by the box and is not a note. Conflict siblings
``<stem>.conflict-<sha>.md`` are skipped here; the box folds them.
"""

from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass, field
from pathlib import PurePosixPath
from typing import Dict, Iterator, List, Optional, Union

TYPE_FOLDERS: Dict[str, str] = {
    "preference": "preferences",
    "person": "people",
    "organization": "organizations",
    "conversation": "conversations",
}
FOLDER_TYPES: Dict[str, str] = {folder: kind for kind, folder in TYPE_FOLDERS.items()}
NOTE_TYPES = tuple(TYPE_FOLDERS)
REQUIRED_HEADER = ("id", "type", "aliases", "updated")
MAX_NOTE_BYTES = 8 * 1024
PROFILE_NAME = "USER.md"

_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_CONFLICT_RE = re.compile(r"\.conflict-[0-9a-fA-F]+\.md$")
_LINK_RE = re.compile(r"\[\[([^\[\]\n|]+?)(?:\|[^\[\]\n]*)?\]\]")
_BULLET_RE = re.compile(
    r"^- (?P<date>\d{4}-\d{2}-\d{2}) (?P<text>.*?)"
    r"(?: \{valid_until: (?P<valid>\d{4}-\d{2}-\d{2})\})?"
    r"(?: \(from: (?P<prov>[^()]*)\))?$"
)
_PLAIN_ALIAS_RE = re.compile(r"^[^\s,\[\]{}\"'#:][^,\[\]{}\"#]*$")


class NoteError(ValueError):
    """A note that cannot be parsed."""


@dataclass
class Fact:
    """One dated bullet. ``provenance`` is the text inside ``(from: ...)``."""

    date: str
    text: str
    valid_until: Optional[str] = None
    provenance: Optional[str] = None

    def render(self) -> str:
        line = f"- {self.date} {self.text}"
        if self.valid_until:
            line += f" {{valid_until: {self.valid_until}}}"
        if self.provenance:
            line += f" (from: {self.provenance})"
        return line


@dataclass
class Note:
    id: str
    type: str
    aliases: List[str] = field(default_factory=list)
    updated: str = ""
    title: str = ""
    # Body lines after the title, in order: Fact for dated bullets, str for anything else.
    body: List[Union[Fact, str]] = field(default_factory=list)
    # Header fields beyond the four required ones, kept verbatim for round-trips.
    extra: Dict[str, str] = field(default_factory=dict)

    @property
    def facts(self) -> List[Fact]:
        return [item for item in self.body if isinstance(item, Fact)]


# -- small helpers -------------------------------------------------------------------------------

def slugify(text: str) -> str:
    """Lowercase ASCII, digits and single hyphens; ``"note"`` when nothing survives."""
    ascii_text = unicodedata.normalize("NFKD", text or "").encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_text.lower()).strip("-")
    return slug[:80].rstrip("-") or "note"


def links(note_or_text: Union[Note, str]) -> List[str]:
    """Ids referenced as ``[[id]]`` (or ``[[id|label]]``), first occurrence order, no duplicates."""
    text = render(note_or_text) if isinstance(note_or_text, Note) else (note_or_text or "")
    return list(dict.fromkeys(match.strip() for match in _LINK_RE.findall(text)))


def is_conflict_sibling(path: Union[str, PurePosixPath]) -> bool:
    return bool(_CONFLICT_RE.search(PurePosixPath(str(path)).name))


def one_line(text: str) -> str:
    """Collapse whitespace so a fact can never add header or bullet lines."""
    return " ".join((text or "").split())


def note_path(note_id: str) -> str:
    return f"{note_id}.md"


def _render_alias(alias: str) -> str:
    return alias if _PLAIN_ALIAS_RE.match(alias) and alias == alias.strip() else json.dumps(alias, ensure_ascii=False)


def _parse_aliases(raw: str) -> List[str]:
    raw = raw.strip()
    if not raw:
        return []
    if not (raw.startswith("[") and raw.endswith("]")):
        return [raw]
    inner, out, i = raw[1:-1], [], 0
    while i < len(inner):
        ch = inner[i]
        if ch in " ,":
            i += 1
        elif ch == '"':
            try:
                value, end = json.JSONDecoder().raw_decode(inner, i)
            except ValueError as exc:
                raise NoteError(f"bad alias quoting: {exc}") from None
            out.append(str(value))
            i = end
        else:
            end = inner.find(",", i)
            end = len(inner) if end < 0 else end
            value = inner[i:end].strip()
            if value:
                out.append(value)
            i = end
    return out


# -- parse / render ------------------------------------------------------------------------------

def parse(text: str) -> Note:
    """Parse a note. Raises NoteError when the header block is missing or malformed."""
    if text.startswith("﻿"):
        text = text[1:]
    lines = text.replace("\r\n", "\n").split("\n")
    if not lines or lines[0].strip() != "---":
        raise NoteError("missing header")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        raise NoteError("unterminated header") from None
    header: Dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep or not key.strip():
            raise NoteError("bad header line")
        value = value.strip()
        if " #" in value and not value.startswith(("[", '"')):
            value = value.split(" #", 1)[0].rstrip()
        header[key.strip()] = value
    body_lines = lines[end + 1:]
    while body_lines and not body_lines[-1].strip():
        body_lines.pop()
    title, body = "", []
    for line in body_lines:
        if not title and line.startswith("# "):
            title = line[2:].strip()
            continue
        if not title and not body and not line.strip():
            continue
        match = _BULLET_RE.match(line)
        if match:
            body.append(Fact(match["date"], match["text"], match["valid"], match["prov"]))
        else:
            body.append(line)
    extra = {k: v for k, v in header.items() if k not in REQUIRED_HEADER}
    return Note(
        id=header.get("id", ""), type=header.get("type", ""),
        aliases=_parse_aliases(header.get("aliases", "")), updated=header.get("updated", ""),
        title=title, body=body, extra=extra,
    )


def render(note: Note) -> str:
    header = [
        "---",
        f"id: {note.id}",
        f"type: {note.type}",
        "aliases: [" + ", ".join(_render_alias(a) for a in note.aliases) + "]",
        f"updated: {note.updated}",
        *(f"{key}: {value}" for key, value in note.extra.items()),
        "---",
    ]
    body = [f"# {note.title or note.id}"]
    body += [item.render() if isinstance(item, Fact) else item for item in note.body]
    return "\n".join(header + body) + "\n"


def new_note(note_id: str, note_type: str, title: str, aliases: Optional[List[str]] = None,
             updated: str = "") -> Note:
    return Note(id=note_id, type=note_type, aliases=list(aliases or []), updated=updated, title=title)


def append_fact(note: Note, text: str, date: str, provenance: Optional[str],
                valid_until: Optional[str] = None) -> Note:
    """Append one dated bullet (single line, provenance without parentheses) and bump ``updated``."""
    if not _DATE_RE.match(date or ""):
        raise NoteError("date must be YYYY-MM-DD")
    if valid_until and not _DATE_RE.match(valid_until):
        raise NoteError("valid_until must be YYYY-MM-DD")
    clean = one_line(text)
    if not clean:
        raise NoteError("empty fact")
    prov = one_line(provenance or "").replace("(", "[").replace(")", "]") or None
    note.body.append(Fact(date, clean, valid_until or None, prov))
    if not note.updated or date > note.updated:
        note.updated = date
    return note


# -- validation ----------------------------------------------------------------------------------

def path_errors(rel_path: Union[str, PurePosixPath]) -> List[str]:
    """Problems with a note's path relative to the notes directory (empty list = fine)."""
    path = PurePosixPath(str(rel_path).replace("\\", "/"))
    errors = []
    if path.is_absolute() or any(part in ("", ".", "..") for part in path.parts):
        errors.append("path must be relative and normalized")
    if any(part.startswith(".") for part in path.parts):
        errors.append("dot-prefixed path component")
    if path.suffix != ".md":
        errors.append("not a .md file")
    if len(path.parts) != 2 or path.parts[0] not in FOLDER_TYPES:
        errors.append("note must sit directly in " + ", ".join(sorted(FOLDER_TYPES)))
    elif not _SLUG_RE.match(path.stem):
        errors.append("file name is not a slug")
    return errors


def validate(rel_path: Union[str, PurePosixPath], content: Union[str, bytes]) -> List[str]:
    """Every problem with a note file (empty list = valid): path, size, UTF-8, header, type/folder, id/path."""
    rel = PurePosixPath(str(rel_path).replace("\\", "/"))
    errors = path_errors(rel)
    raw = content.encode("utf-8") if isinstance(content, str) else content
    if len(raw) > MAX_NOTE_BYTES:
        errors.append(f"note is larger than {MAX_NOTE_BYTES} bytes")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return errors + ["not valid UTF-8"]
    try:
        note = parse(text)
    except NoteError as exc:
        return errors + [str(exc)]
    header_keys = _header_keys(text)
    errors += [f"missing header field: {key}" for key in REQUIRED_HEADER if key not in header_keys]
    if note.type and note.type not in TYPE_FOLDERS:
        errors.append(f"unknown type: {note.type}")
    elif len(rel.parts) == 2 and note.type and FOLDER_TYPES.get(rel.parts[0]) != note.type:
        errors.append("type does not match folder")
    if note.id and note.id != str(rel.with_suffix("")):
        errors.append("id does not match path")
    if note.updated and not _DATE_RE.match(note.updated):
        errors.append("updated is not YYYY-MM-DD")
    return errors


def _header_keys(text: str) -> set:
    lines = text.lstrip("﻿").replace("\r\n", "\n").split("\n")
    keys = set()
    for line in lines[1:]:
        if line.strip() == "---":
            break
        key, sep, value = line.partition(":")
        if sep and key.strip() and (value.strip() or key.strip() == "aliases"):
            keys.add(key.strip())
    return keys


def iter_note_files(root) -> Iterator[str]:
    """Relative POSIX paths of candidate note files under ``root`` (a pathlib.Path): ``*.md`` below
    the type folders, skipping dot components, conflict siblings and USER.md. Validity is the
    caller's job (``validate``)."""
    for folder in sorted(FOLDER_TYPES):
        base = root / folder
        if not base.is_dir() or base.is_symlink():
            continue
        for path in sorted(base.rglob("*.md")):
            rel = path.relative_to(root).as_posix()
            if any(part.startswith(".") for part in PurePosixPath(rel).parts) or is_conflict_sibling(rel):
                continue
            if path.is_symlink() or not path.is_file():
                continue
            yield rel
